# Generated by Django 3.1.3 on 2020-11-22 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campos', '0002_auto_20201121_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLuvia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lluvia_milimetros', models.FloatField(verbose_name='Milímetros')),
                ('lluvia_fecha', models.DateTimeField(verbose_name='Fecha')),
                ('lluvia_campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos.campo', verbose_name='Campo')),
            ],
            options={
                'verbose_name': 'LLuvia',
                'verbose_name_plural': 'LLuvias',
                'ordering': ['lluvia_fecha'],
            },
        ),
    ]
