# Generated by Django 3.1.3 on 2020-11-22 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campo',
            options={'ordering': ['campo_nombre', '-campo_fecha_creacion'], 'verbose_name': 'Campo', 'verbose_name_plural': 'Campos'},
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='campo_created',
            new_name='campo_fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='campo',
            name='campo_fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campo',
            name='campo_hectarea',
            field=models.IntegerField(verbose_name='Cantidad de hectáreas'),
        ),
    ]
